vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        audios:
            uri_prefix: /uploads/audios
            upload_destination: '%kernel.project_dir%/public/uploads/audios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
# prefix url 
# '%kernel.project_dir%/ parametre kernel chemin du projet