controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# delete_image_concert:
#     path: '/delete/image/concert/{id}'
#     controller: App\Controller\ConcertController::deleteImageConcert
#     methods: ['DELETE']